nedokormysh@nedokormysh-VirtualBox:~$ # 2. Подключить репозиторий Docker.
nedokormysh@nedokormysh-VirtualBox:~$ sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Уже установлен пакет ca-certificates самой новой версии (20211016).
Уже установлен пакет curl самой новой версии (7.81.0-1ubuntu1.3).
Следующие НОВЫЕ пакеты будут установлены:
  apt-transport-https gnupg-agent software-properties-common
Обновлено 0 пакетов, установлено 3 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
Необходимо скачать 16,5 kB архивов.
После данной операции объём занятого дискового пространства возрастёт на 232 kB.
Хотите продолжить? [Д/н] y
Пол:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.7 [1 512 B]
Пол:2 http://packages.linuxmint.com vanessa/upstream amd64 software-properties-common all 2.1.9 [9 528 B]
Пол:3 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 gnupg-agent all 2.2.27-3ubuntu2.1 [5 484 B]
Получено 16,5 kB за 1с (31,1 kB/s)         
Выбор ранее не выбранного пакета apt-transport-https.
(Чтение базы данных … на данный момент установлено 320366 файлов и каталогов.)
Подготовка к распаковке …/apt-transport-https_2.4.7_all.deb …
Распаковывается apt-transport-https (2.4.7) …
Выбор ранее не выбранного пакета gnupg-agent.
Подготовка к распаковке …/gnupg-agent_2.2.27-3ubuntu2.1_all.deb …
Распаковывается gnupg-agent (2.2.27-3ubuntu2.1) …
Выбор ранее не выбранного пакета software-properties-common.
Подготовка к распаковке …/software-properties-common_2.1.9_all.deb …
Распаковывается software-properties-common (2.1.9) …
Настраивается пакет apt-transport-https (2.4.7) …
Настраивается пакет software-properties-common (2.1.9) …
Настраивается пакет gnupg-agent (2.2.27-3ubuntu2.1) …
nedokormysh@nedokormysh-VirtualBox:~$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
nedokormysh@nedokormysh-VirtualBox:~$ sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
nedokormysh@nedokormysh-VirtualBox:~$ sudo apt install docker -y
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Будут установлены следующие дополнительные пакеты:
  wmdocker
Следующие НОВЫЕ пакеты будут установлены:
  docker wmdocker
Обновлено 0 пакетов, установлено 2 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.
Необходимо скачать 14,3 kB архивов.
После данной операции объём занятого дискового пространства возрастёт на 58,4 kB.
Пол:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 wmdocker amd64 1.5-2 [13,0 kB]
Пол:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 docker all 1.5-2 [1 316 B]
Получено 14,3 kB за 1с (14,8 kB/s)
Выбор ранее не выбранного пакета wmdocker.
(Чтение базы данных … на данный момент установлено 320377 файлов и каталогов.)
Подготовка к распаковке …/wmdocker_1.5-2_amd64.deb …
Распаковывается wmdocker (1.5-2) …
Выбор ранее не выбранного пакета docker.
Подготовка к распаковке …/archives/docker_1.5-2_all.deb …
Распаковывается docker (1.5-2) …
Настраивается пакет wmdocker (1.5-2) …
Настраивается пакет docker (1.5-2) …
Обрабатываются триггеры для man-db (2.10.2-1) …
nedokormysh@nedokormysh-VirtualBox:~$ sudo apt install docker.io -y
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Будут установлены следующие дополнительные пакеты:
  bridge-utils containerd git git-man liberror-perl pigz runc ubuntu-fan
Предлагаемые пакеты:
  aufs-tools cgroupfs-mount | cgroup-lite debootstrap docker-doc rinse
  git-daemon-run | git-daemon-sysvinit git-doc git-email git-gui gitk gitweb
  git-cvs git-mediawiki git-svn
Следующие НОВЫЕ пакеты будут установлены:
  bridge-utils containerd docker.io git git-man liberror-perl pigz runc
  ubuntu-fan
Обновлено 0 пакетов, установлено 9 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.
Необходимо скачать 69,4 MB архивов.
После данной операции объём занятого дискового пространства возрастёт на 303 MB.
Пол:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 pigz amd64 2.6-1 [63,6 kB]
Пол:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 bridge-utils amd64 1.7-1ubuntu3 [34,4 kB]
Пол:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 runc amd64 1.1.0-0ubuntu1 [4 087 kB]
Пол:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 containerd amd64 1.5.9-0ubuntu3 [27,0 MB]
Пол:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 docker.io amd64 20.10.12-0ubuntu4 [34,0 MB]
Пол:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 liberror-perl all 0.17029-1 [26,5 kB]
Пол:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 git-man all 1:2.34.1-1ubuntu1.4 [952 kB]
Пол:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 git amd64 1:2.34.1-1ubuntu1.4 [3 131 kB]
Пол:9 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ubuntu-fan all 0.12.16 [35,2 kB]
Получено 69,4 MB за 8с (8 556 kB/s)                                            
Предварительная настройка пакетов …
Выбор ранее не выбранного пакета pigz.
(Чтение базы данных … на данный момент установлено 320387 файлов и каталогов.)
Подготовка к распаковке …/0-pigz_2.6-1_amd64.deb …
Распаковывается pigz (2.6-1) …
Выбор ранее не выбранного пакета bridge-utils.
Подготовка к распаковке …/1-bridge-utils_1.7-1ubuntu3_amd64.deb …
Распаковывается bridge-utils (1.7-1ubuntu3) …
Выбор ранее не выбранного пакета runc.
Подготовка к распаковке …/2-runc_1.1.0-0ubuntu1_amd64.deb …
Распаковывается runc (1.1.0-0ubuntu1) …
Выбор ранее не выбранного пакета containerd.
Подготовка к распаковке …/3-containerd_1.5.9-0ubuntu3_amd64.deb …
Распаковывается containerd (1.5.9-0ubuntu3) …
Выбор ранее не выбранного пакета docker.io.
Подготовка к распаковке …/4-docker.io_20.10.12-0ubuntu4_amd64.deb …
Распаковывается docker.io (20.10.12-0ubuntu4) …
Выбор ранее не выбранного пакета liberror-perl.
Подготовка к распаковке …/5-liberror-perl_0.17029-1_all.deb …
Распаковывается liberror-perl (0.17029-1) …
Выбор ранее не выбранного пакета git-man.
Подготовка к распаковке …/6-git-man_1%3a2.34.1-1ubuntu1.4_all.deb …
Распаковывается git-man (1:2.34.1-1ubuntu1.4) …
Выбор ранее не выбранного пакета git.
Подготовка к распаковке …/7-git_1%3a2.34.1-1ubuntu1.4_amd64.deb …
Распаковывается git (1:2.34.1-1ubuntu1.4) …
Выбор ранее не выбранного пакета ubuntu-fan.
Подготовка к распаковке …/8-ubuntu-fan_0.12.16_all.deb …
Распаковывается ubuntu-fan (0.12.16) …
Настраивается пакет runc (1.1.0-0ubuntu1) …
Настраивается пакет liberror-perl (0.17029-1) …
Настраивается пакет bridge-utils (1.7-1ubuntu3) …
Настраивается пакет pigz (2.6-1) …
Настраивается пакет git-man (1:2.34.1-1ubuntu1.4) …
Настраивается пакет containerd (1.5.9-0ubuntu3) …
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service →
 /lib/systemd/system/containerd.service.
Настраивается пакет ubuntu-fan (0.12.16) …
Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-fan.service →
 /lib/systemd/system/ubuntu-fan.service.
Настраивается пакет docker.io (20.10.12-0ubuntu4) …
Добавляется группа «docker» (GID 138) ...
Готово.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /li
b/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/sy
stemd/system/docker.socket.
Настраивается пакет git (1:2.34.1-1ubuntu1.4) …
Обрабатываются триггеры для man-db (2.10.2-1) …
nedokormysh@nedokormysh-VirtualBox:~$ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete 
Digest: sha256:7d246653d0511db2a6b2e0436cfd0e52ac8c066000264b3ce63331ac66dca625
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

nedokormysh@nedokormysh-VirtualBox:~$ docker -v
Docker version 20.10.12, build 20.10.12-0ubuntu4

nedokormysh@nedokormysh-VirtualBox:~$ # 3. Запустить контейнер с Ubuntu.
nedokormysh@nedokormysh-VirtualBox:~$ sudo docker ps -a
CONTAINER ID   IMAGE         COMMAND    CREATED         STATUS                     PORTS     NAMES
9e20f8631d68   hello-world   "/hello"   8 minutes ago   Exited (0) 8 minutes ago             interesting_davinci
nedokormysh@nedokormysh-VirtualBox:~$ sudo docker run ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d19f32bd9e41: Pull complete 
Digest: sha256:34fea4f31bf187bc915536831fd0afc9d214755bf700b5cdb1336c82516d154e
Status: Downloaded newer image for ubuntu:latest
nedokormysh@nedokormysh-VirtualBox:~$ sudo docker ps -a
CONTAINER ID   IMAGE         COMMAND    CREATED          STATUS                      PORTS     NAMES
620be9a970ff   ubuntu        "bash"     36 seconds ago   Exited (0) 30 seconds ago             kind_euclid
9e20f8631d68   hello-world   "/hello"   9 minutes ago    Exited (0) 9 minutes ago              interesting_davinci
nedokormysh@nedokormysh-VirtualBox:~$


nedokormysh@nedokormysh-VirtualBox:~$ # 4. * Используя Dockerfile, собрать связку nginx + PHP-FPM в одном контейнере.
nedokormysh@nedokormysh-VirtualBox:~$ nano Dockerfile 
nedokormysh@nedokormysh-VirtualBox:~$ cat Dockerfile 
FROM ubuntu:latest
MAINTAINER nedokormysh
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install nginx -y
RUN apt-get install php-fpm -y
EXPOSE 80
CMD /usr/sbin/nginx -g "daemon off;"
nedokormysh@nedokormysh-VirtualBox:~$ sudo docker build -t nginx_php-fpm .
Sending build context to Docker daemon  147.5MB
Step 1/9 : FROM ubuntu:latest
 ---> df5de72bdb3b
Step 2/9 : MAINTAINER nedokormysh
 ---> Using cache
 ---> c3369bef153d
Step 3/9 : ENV TZ=Europe/Moscow
 ---> Using cache
 ---> ea1d0437cf65
Step 4/9 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Running in 07b7b4738d83
Removing intermediate container 07b7b4738d83
 ---> f29da850aab5
Step 5/9 : RUN apt-get update
 ---> Running in a9ab81958e98
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [313 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [132 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [333 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4644 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [7791 B]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [264 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [641 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [354 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [5814 B]
Fetched 22.3 MB in 5s (4525 kB/s)
Reading package lists...
Removing intermediate container a9ab81958e98
 ---> 14398556ebc7
Step 6/9 : RUN apt-get install nginx -y
 ---> Running in 8efa43279f9d
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core iproute2 libatm1 libbpf0 libbrotli1
  libbsd0 libcap2-bin libdeflate0 libelf1 libexpat1 libfontconfig1
  libfreetype6 libgd3 libicu70 libjbig0 libjpeg-turbo8 libjpeg8 libmaxminddb0
  libmd0 libmnl0 libnginx-mod-http-geoip2 libnginx-mod-http-image-filter
  libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream
  libnginx-mod-stream-geoip2 libpam-cap libpng16-16 libtiff5 libwebp7 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 libxslt1.1
  libxtables12 nginx-common nginx-core ucf
Suggested packages:
  iproute2-doc libgd-tools mmdb-bin fcgiwrap nginx-doc ssl-cert
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core iproute2 libatm1 libbpf0 libbrotli1
  libbsd0 libcap2-bin libdeflate0 libelf1 libexpat1 libfontconfig1
  libfreetype6 libgd3 libicu70 libjbig0 libjpeg-turbo8 libjpeg8 libmaxminddb0
  libmd0 libmnl0 libnginx-mod-http-geoip2 libnginx-mod-http-image-filter
  libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream
  libnginx-mod-stream-geoip2 libpam-cap libpng16-16 libtiff5 libwebp7 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 libxslt1.1
  libxtables12 nginx nginx-common nginx-core ucf
0 upgraded, 44 newly installed, 0 to remove and 3 not upgraded.
Need to get 17.5 MB of archives.
After this operation, 56.4 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libelf1 amd64 0.186-1build1 [51.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libbpf0 amd64 1:0.5.0-1 [140 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmd0 amd64 1.0.4-1build1 [23.0 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libbsd0 amd64 0.11.5-1 [44.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmnl0 amd64 1.0.4-3build2 [13.2 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtables12 amd64 1.8.7-1ubuntu5 [31.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcap2-bin amd64 1:2.44-1build3 [26.0 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 iproute2 amd64 5.15.0-1ubuntu2 [1070 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatm1 amd64 1:2.5.1-4build2 [22.8 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libexpat1 amd64 2.4.7-1 [90.7 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libicu70 amd64 70.1-2 [10.6 MB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpam-cap amd64 1:2.44-1build3 [7932 B]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libxml2 amd64 2.9.13+dfsg-1ubuntu0.1 [763 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 ucf all 3.0043 [56.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmaxminddb0 amd64 1.5.2-1build2 [24.7 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpng16-16 amd64 1.6.37-3build5 [191 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxau6 amd64 1:1.0.9-1build5 [7634 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxdmcp6 amd64 1:1.1.3-0ubuntu5 [10.9 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb1 amd64 1.14-3ubuntu3 [49.0 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libx11-data all 2:1.7.5-1 [119 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libx11-6 amd64 2:1.7.5-1 [666 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1041 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 fontconfig-config all 2.13.1-4.2ubuntu5 [29.1 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libbrotli1 amd64 1.0.9-2build6 [315 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdeflate0 amd64 1.10-2 [70.9 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libfreetype6 amd64 2.11.1+dfsg-1ubuntu0.1 [389 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfontconfig1 amd64 2.13.1-4.2ubuntu5 [131 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjpeg-turbo8 amd64 2.1.2-0ubuntu1 [134 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjpeg8 amd64 8c-2ubuntu10 [2264 B]
Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjbig0 amd64 2.1-3.1build3 [28.9 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwebp7 amd64 1.2.2-2 [206 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtiff5 amd64 4.3.0-6 [183 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxpm4 amd64 1:3.5.12-1build2 [36.2 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgd3 amd64 2.3.0-2ubuntu2 [129 kB]
Get:35 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 nginx-common all 1.18.0-6ubuntu14.1 [40.1 kB]
Get:36 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnginx-mod-http-geoip2 amd64 1.18.0-6ubuntu14.1 [11.9 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnginx-mod-http-image-filter amd64 1.18.0-6ubuntu14.1 [15.4 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxslt1.1 amd64 1.1.34-4build2 [164 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnginx-mod-http-xslt-filter amd64 1.18.0-6ubuntu14.1 [13.8 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnginx-mod-mail amd64 1.18.0-6ubuntu14.1 [45.7 kB]
Get:41 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnginx-mod-stream amd64 1.18.0-6ubuntu14.1 [72.9 kB]
Get:42 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnginx-mod-stream-geoip2 amd64 1.18.0-6ubuntu14.1 [10.1 kB]
Get:43 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 nginx-core amd64 1.18.0-6ubuntu14.1 [482 kB]
Get:44 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 nginx amd64 1.18.0-6ubuntu14.1 [3884 B]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 17.5 MB in 3s (5509 kB/s)
Selecting previously unselected package libelf1:amd64.
(Reading database ... 4395 files and directories currently installed.)
Preparing to unpack .../00-libelf1_0.186-1build1_amd64.deb ...
Unpacking libelf1:amd64 (0.186-1build1) ...
Selecting previously unselected package libbpf0:amd64.
Preparing to unpack .../01-libbpf0_1%3a0.5.0-1_amd64.deb ...
Unpacking libbpf0:amd64 (1:0.5.0-1) ...
Selecting previously unselected package libmd0:amd64.
Preparing to unpack .../02-libmd0_1.0.4-1build1_amd64.deb ...
Unpacking libmd0:amd64 (1.0.4-1build1) ...
Selecting previously unselected package libbsd0:amd64.
Preparing to unpack .../03-libbsd0_0.11.5-1_amd64.deb ...
Unpacking libbsd0:amd64 (0.11.5-1) ...
Selecting previously unselected package libmnl0:amd64.
Preparing to unpack .../04-libmnl0_1.0.4-3build2_amd64.deb ...
Unpacking libmnl0:amd64 (1.0.4-3build2) ...
Selecting previously unselected package libxtables12:amd64.
Preparing to unpack .../05-libxtables12_1.8.7-1ubuntu5_amd64.deb ...
Unpacking libxtables12:amd64 (1.8.7-1ubuntu5) ...
Selecting previously unselected package libcap2-bin.
Preparing to unpack .../06-libcap2-bin_1%3a2.44-1build3_amd64.deb ...
Unpacking libcap2-bin (1:2.44-1build3) ...
Selecting previously unselected package iproute2.
Preparing to unpack .../07-iproute2_5.15.0-1ubuntu2_amd64.deb ...
Unpacking iproute2 (5.15.0-1ubuntu2) ...
Selecting previously unselected package libatm1:amd64.
Preparing to unpack .../08-libatm1_1%3a2.5.1-4build2_amd64.deb ...
Unpacking libatm1:amd64 (1:2.5.1-4build2) ...
Selecting previously unselected package libexpat1:amd64.
Preparing to unpack .../09-libexpat1_2.4.7-1_amd64.deb ...
Unpacking libexpat1:amd64 (2.4.7-1) ...
Selecting previously unselected package libicu70:amd64.
Preparing to unpack .../10-libicu70_70.1-2_amd64.deb ...
Unpacking libicu70:amd64 (70.1-2) ...
Selecting previously unselected package libpam-cap:amd64.
Preparing to unpack .../11-libpam-cap_1%3a2.44-1build3_amd64.deb ...
Unpacking libpam-cap:amd64 (1:2.44-1build3) ...
Selecting previously unselected package libxml2:amd64.
Preparing to unpack .../12-libxml2_2.9.13+dfsg-1ubuntu0.1_amd64.deb ...
Unpacking libxml2:amd64 (2.9.13+dfsg-1ubuntu0.1) ...
Selecting previously unselected package ucf.
Preparing to unpack .../13-ucf_3.0043_all.deb ...
Moving old data out of the way
Unpacking ucf (3.0043) ...
Selecting previously unselected package libmaxminddb0:amd64.
Preparing to unpack .../14-libmaxminddb0_1.5.2-1build2_amd64.deb ...
Unpacking libmaxminddb0:amd64 (1.5.2-1build2) ...
Selecting previously unselected package libpng16-16:amd64.
Preparing to unpack .../15-libpng16-16_1.6.37-3build5_amd64.deb ...
Unpacking libpng16-16:amd64 (1.6.37-3build5) ...
Selecting previously unselected package libxau6:amd64.
Preparing to unpack .../16-libxau6_1%3a1.0.9-1build5_amd64.deb ...
Unpacking libxau6:amd64 (1:1.0.9-1build5) ...
Selecting previously unselected package libxdmcp6:amd64.
Preparing to unpack .../17-libxdmcp6_1%3a1.1.3-0ubuntu5_amd64.deb ...
Unpacking libxdmcp6:amd64 (1:1.1.3-0ubuntu5) ...
Selecting previously unselected package libxcb1:amd64.
Preparing to unpack .../18-libxcb1_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb1:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libx11-data.
Preparing to unpack .../19-libx11-data_2%3a1.7.5-1_all.deb ...
Unpacking libx11-data (2:1.7.5-1) ...
Selecting previously unselected package libx11-6:amd64.
Preparing to unpack .../20-libx11-6_2%3a1.7.5-1_amd64.deb ...
Unpacking libx11-6:amd64 (2:1.7.5-1) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../21-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fontconfig-config.
Preparing to unpack .../22-fontconfig-config_2.13.1-4.2ubuntu5_all.deb ...
Unpacking fontconfig-config (2.13.1-4.2ubuntu5) ...
Selecting previously unselected package libbrotli1:amd64.
Preparing to unpack .../23-libbrotli1_1.0.9-2build6_amd64.deb ...
Unpacking libbrotli1:amd64 (1.0.9-2build6) ...
Selecting previously unselected package libdeflate0:amd64.
Preparing to unpack .../24-libdeflate0_1.10-2_amd64.deb ...
Unpacking libdeflate0:amd64 (1.10-2) ...
Selecting previously unselected package libfreetype6:amd64.
Preparing to unpack .../25-libfreetype6_2.11.1+dfsg-1ubuntu0.1_amd64.deb ...
Unpacking libfreetype6:amd64 (2.11.1+dfsg-1ubuntu0.1) ...
Selecting previously unselected package libfontconfig1:amd64.
Preparing to unpack .../26-libfontconfig1_2.13.1-4.2ubuntu5_amd64.deb ...
Unpacking libfontconfig1:amd64 (2.13.1-4.2ubuntu5) ...
Selecting previously unselected package libjpeg-turbo8:amd64.
Preparing to unpack .../27-libjpeg-turbo8_2.1.2-0ubuntu1_amd64.deb ...
Unpacking libjpeg-turbo8:amd64 (2.1.2-0ubuntu1) ...
Selecting previously unselected package libjpeg8:amd64.
Preparing to unpack .../28-libjpeg8_8c-2ubuntu10_amd64.deb ...
Unpacking libjpeg8:amd64 (8c-2ubuntu10) ...
Selecting previously unselected package libjbig0:amd64.
Preparing to unpack .../29-libjbig0_2.1-3.1build3_amd64.deb ...
Unpacking libjbig0:amd64 (2.1-3.1build3) ...
Selecting previously unselected package libwebp7:amd64.
Preparing to unpack .../30-libwebp7_1.2.2-2_amd64.deb ...
Unpacking libwebp7:amd64 (1.2.2-2) ...
Selecting previously unselected package libtiff5:amd64.
Preparing to unpack .../31-libtiff5_4.3.0-6_amd64.deb ...
Unpacking libtiff5:amd64 (4.3.0-6) ...
Selecting previously unselected package libxpm4:amd64.
Preparing to unpack .../32-libxpm4_1%3a3.5.12-1build2_amd64.deb ...
Unpacking libxpm4:amd64 (1:3.5.12-1build2) ...
Selecting previously unselected package libgd3:amd64.
Preparing to unpack .../33-libgd3_2.3.0-2ubuntu2_amd64.deb ...
Unpacking libgd3:amd64 (2.3.0-2ubuntu2) ...
Selecting previously unselected package nginx-common.
Preparing to unpack .../34-nginx-common_1.18.0-6ubuntu14.1_all.deb ...
Unpacking nginx-common (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package libnginx-mod-http-geoip2.
Preparing to unpack .../35-libnginx-mod-http-geoip2_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking libnginx-mod-http-geoip2 (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package libnginx-mod-http-image-filter.
Preparing to unpack .../36-libnginx-mod-http-image-filter_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking libnginx-mod-http-image-filter (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package libxslt1.1:amd64.
Preparing to unpack .../37-libxslt1.1_1.1.34-4build2_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.34-4build2) ...
Selecting previously unselected package libnginx-mod-http-xslt-filter.
Preparing to unpack .../38-libnginx-mod-http-xslt-filter_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking libnginx-mod-http-xslt-filter (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package libnginx-mod-mail.
Preparing to unpack .../39-libnginx-mod-mail_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking libnginx-mod-mail (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package libnginx-mod-stream.
Preparing to unpack .../40-libnginx-mod-stream_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking libnginx-mod-stream (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package libnginx-mod-stream-geoip2.
Preparing to unpack .../41-libnginx-mod-stream-geoip2_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking libnginx-mod-stream-geoip2 (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package nginx-core.
Preparing to unpack .../42-nginx-core_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking nginx-core (1.18.0-6ubuntu14.1) ...
Selecting previously unselected package nginx.
Preparing to unpack .../43-nginx_1.18.0-6ubuntu14.1_amd64.deb ...
Unpacking nginx (1.18.0-6ubuntu14.1) ...
Setting up libexpat1:amd64 (2.4.7-1) ...
Setting up libxau6:amd64 (1:1.0.9-1build5) ...
Setting up libmaxminddb0:amd64 (1.5.2-1build2) ...
Setting up libbrotli1:amd64 (1.0.9-2build6) ...
Setting up libdeflate0:amd64 (1.10-2) ...
Setting up nginx-common (1.18.0-6ubuntu14.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libatm1:amd64 (1:2.5.1-4build2) ...
Setting up libjbig0:amd64 (2.1-3.1build3) ...
Setting up libcap2-bin (1:2.44-1build3) ...
Setting up libx11-data (2:1.7.5-1) ...
Setting up libpng16-16:amd64 (1.6.37-3build5) ...
Setting up libmnl0:amd64 (1.0.4-3build2) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up ucf (3.0043) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libjpeg-turbo8:amd64 (2.1.2-0ubuntu1) ...
Setting up libxtables12:amd64 (1.8.7-1ubuntu5) ...
Setting up libwebp7:amd64 (1.2.2-2) ...
Setting up libmd0:amd64 (1.0.4-1build1) ...
Setting up libnginx-mod-http-geoip2 (1.18.0-6ubuntu14.1) ...
Setting up libbsd0:amd64 (0.11.5-1) ...
Setting up libelf1:amd64 (0.186-1build1) ...
Setting up libpam-cap:amd64 (1:2.44-1build3) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libicu70:amd64 (70.1-2) ...
Setting up libjpeg8:amd64 (8c-2ubuntu10) ...
Setting up libnginx-mod-mail (1.18.0-6ubuntu14.1) ...
Setting up libxdmcp6:amd64 (1:1.1.3-0ubuntu5) ...
Setting up libxcb1:amd64 (1.14-3ubuntu3) ...
Setting up fontconfig-config (2.13.1-4.2ubuntu5) ...
Setting up libnginx-mod-stream (1.18.0-6ubuntu14.1) ...
Setting up libfreetype6:amd64 (2.11.1+dfsg-1ubuntu0.1) ...
Setting up libx11-6:amd64 (2:1.7.5-1) ...
Setting up libtiff5:amd64 (4.3.0-6) ...
Setting up libfontconfig1:amd64 (2.13.1-4.2ubuntu5) ...
Setting up libbpf0:amd64 (1:0.5.0-1) ...
Setting up libnginx-mod-stream-geoip2 (1.18.0-6ubuntu14.1) ...
Setting up libxml2:amd64 (2.9.13+dfsg-1ubuntu0.1) ...
Setting up libxpm4:amd64 (1:3.5.12-1build2) ...
Setting up iproute2 (5.15.0-1ubuntu2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libgd3:amd64 (2.3.0-2ubuntu2) ...
Setting up libxslt1.1:amd64 (1.1.34-4build2) ...
Setting up libnginx-mod-http-image-filter (1.18.0-6ubuntu14.1) ...
Setting up libnginx-mod-http-xslt-filter (1.18.0-6ubuntu14.1) ...
Setting up nginx-core (1.18.0-6ubuntu14.1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up nginx (1.18.0-6ubuntu14.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Removing intermediate container 8efa43279f9d
 ---> 049a88c2e4cb
Step 7/9 : RUN apt-get install php-fpm -y
 ---> Running in 0216ff5238b7
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  bzip2 dbus dmsetup file gir1.2-glib-2.0 libapparmor1 libargon2-1
  libcryptsetup12 libdbus-1-3 libdevmapper1.02.1 libedit2 libgdbm-compat4
  libgdbm6 libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libip4tc2
  libjson-c5 libkmod2 libmagic-mgc libmagic1 libmpdec3 libperl5.34
  libpython3-stdlib libpython3.10-minimal libpython3.10-stdlib libreadline8
  libsodium23 libsqlite3-0 mailcap media-types mime-support netbase
  networkd-dispatcher perl perl-modules-5.34 php-common php8.1-cli
  php8.1-common php8.1-fpm php8.1-opcache php8.1-readline psmisc python3
  python3-dbus python3-gi python3-minimal python3.10 python3.10-minimal
  readline-common shared-mime-info systemd systemd-timesyncd tzdata
  xdg-user-dirs xz-utils
Suggested packages:
  bzip2-doc default-dbus-session-bus | dbus-session-bus gdbm-l10n iw
  | wireless-tools perl-doc libterm-readline-gnu-perl
  | libterm-readline-perl-perl make libtap-harness-archive-perl php-pear
  python3-doc python3-tk python3-venv python-dbus-doc python3.10-venv
  python3.10-doc binutils binfmt-support readline-doc systemd-container
  libfido2-1 libtss2-esys-3.0.2-0 libtss2-mu0 libtss2-rc0 policykit-1
The following NEW packages will be installed:
  bzip2 dbus dmsetup file gir1.2-glib-2.0 libapparmor1 libargon2-1
  libcryptsetup12 libdbus-1-3 libdevmapper1.02.1 libedit2 libgdbm-compat4
  libgdbm6 libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libip4tc2
  libjson-c5 libkmod2 libmagic-mgc libmagic1 libmpdec3 libperl5.34
  libpython3-stdlib libpython3.10-minimal libpython3.10-stdlib libreadline8
  libsodium23 libsqlite3-0 mailcap media-types mime-support netbase
  networkd-dispatcher perl perl-modules-5.34 php-common php-fpm php8.1-cli
  php8.1-common php8.1-fpm php8.1-opcache php8.1-readline psmisc python3
  python3-dbus python3-gi python3-minimal python3.10 python3.10-minimal
  readline-common shared-mime-info systemd systemd-timesyncd tzdata
  xdg-user-dirs xz-utils
0 upgraded, 57 newly installed, 0 to remove and 3 not upgraded.
Need to get 29.0 MB of archives.
After this operation, 136 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-minimal amd64 3.10.4-3ubuntu0.1 [809 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-minimal amd64 3.10.4-3ubuntu0.1 [2258 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 python3-minimal amd64 3.10.4-0ubuntu2 [24.4 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 media-types all 7.0.0 [25.5 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 perl-modules-5.34 all 5.34.0-3ubuntu1 [2975 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgdbm6 amd64 1.23-1 [33.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgdbm-compat4 amd64 1.23-1 [6606 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libperl5.34 amd64 5.34.0-3ubuntu1 [4809 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 perl amd64 5.34.0-3ubuntu1 [232 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 mailcap all 3.70+nmu1ubuntu1 [23.8 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 mime-support all 3.66 [3696 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmpdec3 amd64 2.5.1-2build2 [86.8 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 readline-common all 8.1.2-1 [53.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libreadline8 amd64 8.1.2-1 [153 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsqlite3-0 amd64 3.37.2-2 [643 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-stdlib amd64 3.10.4-3ubuntu0.1 [1830 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10 amd64 3.10.4-3ubuntu0.1 [488 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpython3-stdlib amd64 3.10.4-0ubuntu2 [6990 B]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 python3 amd64 3.10.4-0ubuntu2 [22.8 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libapparmor1 amd64 3.0.4-2ubuntu2.1 [38.7 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libargon2-1 amd64 0~20171227-0.3 [19.5 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdevmapper1.02.1 amd64 2:1.02.175-2.1ubuntu4 [139 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjson-c5 amd64 0.15-3~ubuntu1.22.04.1 [33.5 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcryptsetup12 amd64 2:2.4.3-1ubuntu1.1 [211 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 libip4tc2 amd64 1.8.7-1ubuntu5 [19.7 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy/main amd64 libkmod2 amd64 29-1ubuntu1 [48.0 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd amd64 249.11-0ubuntu3.4 [4580 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdbus-1-3 amd64 1.12.20-2ubuntu4 [188 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 dbus amd64 1.12.20-2ubuntu4 [158 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 dmsetup amd64 2:1.02.175-2.1ubuntu4 [81.7 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglib2.0-0 amd64 2.72.1-1 [1460 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgirepository-1.0-1 amd64 1.72.0-1 [55.6 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 gir1.2-glib-2.0 amd64 1.72.0-1 [164 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglib2.0-data all 2.72.1-1 [4908 B]
Get:35 http://archive.ubuntu.com/ubuntu jammy/main amd64 netbase all 6.3 [12.9 kB]
Get:36 http://archive.ubuntu.com/ubuntu jammy/main amd64 python3-dbus amd64 1.2.18-3build1 [99.5 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-gi amd64 3.42.1-0ubuntu1 [229 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 networkd-dispatcher all 2.1-2ubuntu0.22.04.2 [15.8 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy/main amd64 shared-mime-info amd64 2.1-2 [454 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd-timesyncd amd64 249.11-0ubuntu3.4 [31.2 kB]
Get:41 http://archive.ubuntu.com/ubuntu jammy/main amd64 tzdata all 2022a-0ubuntu1 [342 kB]
Get:42 http://archive.ubuntu.com/ubuntu jammy/main amd64 xdg-user-dirs amd64 0.17-2ubuntu4 [53.9 kB]
Get:43 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmagic-mgc amd64 1:5.41-3 [257 kB]
Get:44 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmagic1 amd64 1:5.41-3 [87.2 kB]
Get:45 http://archive.ubuntu.com/ubuntu jammy/main amd64 file amd64 1:5.41-3 [21.5 kB]
Get:46 http://archive.ubuntu.com/ubuntu jammy/main amd64 libedit2 amd64 3.1-20210910-1build1 [96.8 kB]
Get:47 http://archive.ubuntu.com/ubuntu jammy/main amd64 psmisc amd64 23.4-2build3 [119 kB]
Get:48 http://archive.ubuntu.com/ubuntu jammy/main amd64 xz-utils amd64 5.2.5-2ubuntu1 [84.8 kB]
Get:49 http://archive.ubuntu.com/ubuntu jammy/main amd64 bzip2 amd64 1.0.8-5build1 [34.8 kB]
Get:50 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsodium23 amd64 1.0.18-1build2 [164 kB]
Get:51 http://archive.ubuntu.com/ubuntu jammy/main amd64 php-common all 2:92ubuntu1 [12.4 kB]
Get:52 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 php8.1-common amd64 8.1.2-1ubuntu2.2 [1123 kB]
Get:53 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 php8.1-opcache amd64 8.1.2-1ubuntu2.2 [365 kB]
Get:54 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 php8.1-readline amd64 8.1.2-1ubuntu2.2 [13.5 kB]
Get:55 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 php8.1-cli amd64 8.1.2-1ubuntu2.2 [1825 kB]
Get:56 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 php8.1-fpm amd64 8.1.2-1ubuntu2.2 [1839 kB]
Get:57 http://archive.ubuntu.com/ubuntu jammy/universe amd64 php-fpm all 2:8.1+92ubuntu1 [2838 B]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 29.0 MB in 3s (9865 kB/s)
Selecting previously unselected package libpython3.10-minimal:amd64.
(Reading database ... 5298 files and directories currently installed.)
Preparing to unpack .../libpython3.10-minimal_3.10.4-3ubuntu0.1_amd64.deb ...
Unpacking libpython3.10-minimal:amd64 (3.10.4-3ubuntu0.1) ...
Selecting previously unselected package python3.10-minimal.
Preparing to unpack .../python3.10-minimal_3.10.4-3ubuntu0.1_amd64.deb ...
Unpacking python3.10-minimal (3.10.4-3ubuntu0.1) ...
Setting up libpython3.10-minimal:amd64 (3.10.4-3ubuntu0.1) ...
Setting up python3.10-minimal (3.10.4-3ubuntu0.1) ...
Selecting previously unselected package python3-minimal.
(Reading database ... 5592 files and directories currently installed.)
Preparing to unpack .../00-python3-minimal_3.10.4-0ubuntu2_amd64.deb ...
Unpacking python3-minimal (3.10.4-0ubuntu2) ...
Selecting previously unselected package media-types.
Preparing to unpack .../01-media-types_7.0.0_all.deb ...
Unpacking media-types (7.0.0) ...
Selecting previously unselected package perl-modules-5.34.
Preparing to unpack .../02-perl-modules-5.34_5.34.0-3ubuntu1_all.deb ...
Unpacking perl-modules-5.34 (5.34.0-3ubuntu1) ...
Selecting previously unselected package libgdbm6:amd64.
Preparing to unpack .../03-libgdbm6_1.23-1_amd64.deb ...
Unpacking libgdbm6:amd64 (1.23-1) ...
Selecting previously unselected package libgdbm-compat4:amd64.
Preparing to unpack .../04-libgdbm-compat4_1.23-1_amd64.deb ...
Unpacking libgdbm-compat4:amd64 (1.23-1) ...
Selecting previously unselected package libperl5.34:amd64.
Preparing to unpack .../05-libperl5.34_5.34.0-3ubuntu1_amd64.deb ...
Unpacking libperl5.34:amd64 (5.34.0-3ubuntu1) ...
Selecting previously unselected package perl.
Preparing to unpack .../06-perl_5.34.0-3ubuntu1_amd64.deb ...
Unpacking perl (5.34.0-3ubuntu1) ...
Selecting previously unselected package mailcap.
Preparing to unpack .../07-mailcap_3.70+nmu1ubuntu1_all.deb ...
Unpacking mailcap (3.70+nmu1ubuntu1) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../08-mime-support_3.66_all.deb ...
Unpacking mime-support (3.66) ...
Selecting previously unselected package libmpdec3:amd64.
Preparing to unpack .../09-libmpdec3_2.5.1-2build2_amd64.deb ...
Unpacking libmpdec3:amd64 (2.5.1-2build2) ...
Selecting previously unselected package readline-common.
Preparing to unpack .../10-readline-common_8.1.2-1_all.deb ...
Unpacking readline-common (8.1.2-1) ...
Selecting previously unselected package libreadline8:amd64.
Preparing to unpack .../11-libreadline8_8.1.2-1_amd64.deb ...
Unpacking libreadline8:amd64 (8.1.2-1) ...
Selecting previously unselected package libsqlite3-0:amd64.
Preparing to unpack .../12-libsqlite3-0_3.37.2-2_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.37.2-2) ...
Selecting previously unselected package libpython3.10-stdlib:amd64.
Preparing to unpack .../13-libpython3.10-stdlib_3.10.4-3ubuntu0.1_amd64.deb ...
Unpacking libpython3.10-stdlib:amd64 (3.10.4-3ubuntu0.1) ...
Selecting previously unselected package python3.10.
Preparing to unpack .../14-python3.10_3.10.4-3ubuntu0.1_amd64.deb ...
Unpacking python3.10 (3.10.4-3ubuntu0.1) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../15-libpython3-stdlib_3.10.4-0ubuntu2_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.10.4-0ubuntu2) ...
Setting up python3-minimal (3.10.4-0ubuntu2) ...
Selecting previously unselected package python3.
(Reading database ... 8034 files and directories currently installed.)
Preparing to unpack .../00-python3_3.10.4-0ubuntu2_amd64.deb ...
Unpacking python3 (3.10.4-0ubuntu2) ...
Selecting previously unselected package libapparmor1:amd64.
Preparing to unpack .../01-libapparmor1_3.0.4-2ubuntu2.1_amd64.deb ...
Unpacking libapparmor1:amd64 (3.0.4-2ubuntu2.1) ...
Selecting previously unselected package libargon2-1:amd64.
Preparing to unpack .../02-libargon2-1_0~20171227-0.3_amd64.deb ...
Unpacking libargon2-1:amd64 (0~20171227-0.3) ...
Selecting previously unselected package libdevmapper1.02.1:amd64.
Preparing to unpack .../03-libdevmapper1.02.1_2%3a1.02.175-2.1ubuntu4_amd64.deb ...
Unpacking libdevmapper1.02.1:amd64 (2:1.02.175-2.1ubuntu4) ...
Selecting previously unselected package libjson-c5:amd64.
Preparing to unpack .../04-libjson-c5_0.15-3~ubuntu1.22.04.1_amd64.deb ...
Unpacking libjson-c5:amd64 (0.15-3~ubuntu1.22.04.1) ...
Selecting previously unselected package libcryptsetup12:amd64.
Preparing to unpack .../05-libcryptsetup12_2%3a2.4.3-1ubuntu1.1_amd64.deb ...
Unpacking libcryptsetup12:amd64 (2:2.4.3-1ubuntu1.1) ...
Selecting previously unselected package libip4tc2:amd64.
Preparing to unpack .../06-libip4tc2_1.8.7-1ubuntu5_amd64.deb ...
Unpacking libip4tc2:amd64 (1.8.7-1ubuntu5) ...
Selecting previously unselected package libkmod2:amd64.
Preparing to unpack .../07-libkmod2_29-1ubuntu1_amd64.deb ...
Unpacking libkmod2:amd64 (29-1ubuntu1) ...
Selecting previously unselected package systemd.
Preparing to unpack .../08-systemd_249.11-0ubuntu3.4_amd64.deb ...
Unpacking systemd (249.11-0ubuntu3.4) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../09-libdbus-1-3_1.12.20-2ubuntu4_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.12.20-2ubuntu4) ...
Selecting previously unselected package dbus.
Preparing to unpack .../10-dbus_1.12.20-2ubuntu4_amd64.deb ...
Unpacking dbus (1.12.20-2ubuntu4) ...
Selecting previously unselected package dmsetup.
Preparing to unpack .../11-dmsetup_2%3a1.02.175-2.1ubuntu4_amd64.deb ...
Unpacking dmsetup (2:1.02.175-2.1ubuntu4) ...
Selecting previously unselected package libglib2.0-0:amd64.
Preparing to unpack .../12-libglib2.0-0_2.72.1-1_amd64.deb ...
Unpacking libglib2.0-0:amd64 (2.72.1-1) ...
Selecting previously unselected package libgirepository-1.0-1:amd64.
Preparing to unpack .../13-libgirepository-1.0-1_1.72.0-1_amd64.deb ...
Unpacking libgirepository-1.0-1:amd64 (1.72.0-1) ...
Selecting previously unselected package gir1.2-glib-2.0:amd64.
Preparing to unpack .../14-gir1.2-glib-2.0_1.72.0-1_amd64.deb ...
Unpacking gir1.2-glib-2.0:amd64 (1.72.0-1) ...
Selecting previously unselected package libglib2.0-data.
Preparing to unpack .../15-libglib2.0-data_2.72.1-1_all.deb ...
Unpacking libglib2.0-data (2.72.1-1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../16-netbase_6.3_all.deb ...
Unpacking netbase (6.3) ...
Selecting previously unselected package python3-dbus.
Preparing to unpack .../17-python3-dbus_1.2.18-3build1_amd64.deb ...
Unpacking python3-dbus (1.2.18-3build1) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../18-python3-gi_3.42.1-0ubuntu1_amd64.deb ...
Unpacking python3-gi (3.42.1-0ubuntu1) ...
Selecting previously unselected package networkd-dispatcher.
Preparing to unpack .../19-networkd-dispatcher_2.1-2ubuntu0.22.04.2_all.deb ...
Unpacking networkd-dispatcher (2.1-2ubuntu0.22.04.2) ...
Selecting previously unselected package shared-mime-info.
Preparing to unpack .../20-shared-mime-info_2.1-2_amd64.deb ...
Unpacking shared-mime-info (2.1-2) ...
Selecting previously unselected package systemd-timesyncd.
Preparing to unpack .../21-systemd-timesyncd_249.11-0ubuntu3.4_amd64.deb ...
Unpacking systemd-timesyncd (249.11-0ubuntu3.4) ...
Selecting previously unselected package tzdata.
Preparing to unpack .../22-tzdata_2022a-0ubuntu1_all.deb ...
Unpacking tzdata (2022a-0ubuntu1) ...
Selecting previously unselected package xdg-user-dirs.
Preparing to unpack .../23-xdg-user-dirs_0.17-2ubuntu4_amd64.deb ...
Unpacking xdg-user-dirs (0.17-2ubuntu4) ...
Selecting previously unselected package libmagic-mgc.
Preparing to unpack .../24-libmagic-mgc_1%3a5.41-3_amd64.deb ...
Unpacking libmagic-mgc (1:5.41-3) ...
Selecting previously unselected package libmagic1:amd64.
Preparing to unpack .../25-libmagic1_1%3a5.41-3_amd64.deb ...
Unpacking libmagic1:amd64 (1:5.41-3) ...
Selecting previously unselected package file.
Preparing to unpack .../26-file_1%3a5.41-3_amd64.deb ...
Unpacking file (1:5.41-3) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../27-libedit2_3.1-20210910-1build1_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20210910-1build1) ...
Selecting previously unselected package psmisc.
Preparing to unpack .../28-psmisc_23.4-2build3_amd64.deb ...
Unpacking psmisc (23.4-2build3) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../29-xz-utils_5.2.5-2ubuntu1_amd64.deb ...
Unpacking xz-utils (5.2.5-2ubuntu1) ...
Selecting previously unselected package bzip2.
Preparing to unpack .../30-bzip2_1.0.8-5build1_amd64.deb ...
Unpacking bzip2 (1.0.8-5build1) ...
Selecting previously unselected package libsodium23:amd64.
Preparing to unpack .../31-libsodium23_1.0.18-1build2_amd64.deb ...
Unpacking libsodium23:amd64 (1.0.18-1build2) ...
Selecting previously unselected package php-common.
Preparing to unpack .../32-php-common_2%3a92ubuntu1_all.deb ...
Unpacking php-common (2:92ubuntu1) ...
Selecting previously unselected package php8.1-common.
Preparing to unpack .../33-php8.1-common_8.1.2-1ubuntu2.2_amd64.deb ...
Unpacking php8.1-common (8.1.2-1ubuntu2.2) ...
Selecting previously unselected package php8.1-opcache.
Preparing to unpack .../34-php8.1-opcache_8.1.2-1ubuntu2.2_amd64.deb ...
Unpacking php8.1-opcache (8.1.2-1ubuntu2.2) ...
Selecting previously unselected package php8.1-readline.
Preparing to unpack .../35-php8.1-readline_8.1.2-1ubuntu2.2_amd64.deb ...
Unpacking php8.1-readline (8.1.2-1ubuntu2.2) ...
Selecting previously unselected package php8.1-cli.
Preparing to unpack .../36-php8.1-cli_8.1.2-1ubuntu2.2_amd64.deb ...
Unpacking php8.1-cli (8.1.2-1ubuntu2.2) ...
Selecting previously unselected package php8.1-fpm.
Preparing to unpack .../37-php8.1-fpm_8.1.2-1ubuntu2.2_amd64.deb ...
Unpacking php8.1-fpm (8.1.2-1ubuntu2.2) ...
Selecting previously unselected package php-fpm.
Preparing to unpack .../38-php-fpm_2%3a8.1+92ubuntu1_all.deb ...
Unpacking php-fpm (2:8.1+92ubuntu1) ...
Setting up libip4tc2:amd64 (1.8.7-1ubuntu5) ...
Setting up media-types (7.0.0) ...
Setting up libapparmor1:amd64 (3.0.4-2ubuntu2.1) ...
Setting up libsodium23:amd64 (1.0.18-1build2) ...
Setting up xdg-user-dirs (0.17-2ubuntu4) ...
Setting up libmagic-mgc (1:5.41-3) ...
Setting up psmisc (23.4-2build3) ...
Setting up libglib2.0-0:amd64 (2.72.1-1) ...
No schema files found: doing nothing.
Setting up libargon2-1:amd64 (0~20171227-0.3) ...
Setting up libedit2:amd64 (3.1-20210910-1build1) ...
Setting up libsqlite3-0:amd64 (3.37.2-2) ...
Setting up libmagic1:amd64 (1:5.41-3) ...
Setting up file (1:5.41-3) ...
Setting up perl-modules-5.34 (5.34.0-3ubuntu1) ...
Setting up bzip2 (1.0.8-5build1) ...
Setting up tzdata (2022a-0ubuntu1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Current default time zone: 'Europe/Moscow'
Local time is now:      Wed Aug 17 21:30:33 MSK 2022.
Universal Time is now:  Wed Aug 17 18:30:33 UTC 2022.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up libglib2.0-data (2.72.1-1) ...
Setting up libdbus-1-3:amd64 (1.12.20-2ubuntu4) ...
Setting up dbus (1.12.20-2ubuntu4) ...
Setting up xz-utils (5.2.5-2ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up shared-mime-info (2.1-2) ...
Setting up libdevmapper1.02.1:amd64 (2:1.02.175-2.1ubuntu4) ...
Setting up dmsetup (2:1.02.175-2.1ubuntu4) ...
Setting up libmpdec3:amd64 (2.5.1-2build2) ...
Setting up libgirepository-1.0-1:amd64 (1.72.0-1) ...
Setting up netbase (6.3) ...
Setting up libjson-c5:amd64 (0.15-3~ubuntu1.22.04.1) ...
Setting up readline-common (8.1.2-1) ...
Setting up libkmod2:amd64 (29-1ubuntu1) ...
Setting up libgdbm6:amd64 (1.23-1) ...
Setting up php-common (2:92ubuntu1) ...
Created symlink /etc/systemd/system/timers.target.wants/phpsessionclean.timer → /lib/systemd/system/phpsessionclean.timer.
Setting up php8.1-common (8.1.2-1ubuntu2.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/calendar.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/ctype.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/exif.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/fileinfo.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/ffi.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/ftp.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/gettext.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/iconv.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/pdo.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/phar.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/posix.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/shmop.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/sockets.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/sysvmsg.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/sysvsem.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/sysvshm.ini with new version
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/tokenizer.ini with new version
Setting up libreadline8:amd64 (8.1.2-1) ...
Setting up libpython3.10-stdlib:amd64 (3.10.4-3ubuntu0.1) ...
Setting up libgdbm-compat4:amd64 (1.23-1) ...
Setting up gir1.2-glib-2.0:amd64 (1.72.0-1) ...
Setting up libcryptsetup12:amd64 (2:2.4.3-1ubuntu1.1) ...
Setting up php8.1-readline (8.1.2-1ubuntu2.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/readline.ini with new version
Setting up php8.1-opcache (8.1.2-1ubuntu2.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/mods-available/opcache.ini with new version
Setting up libpython3-stdlib:amd64 (3.10.4-0ubuntu2) ...
Setting up libperl5.34:amd64 (5.34.0-3ubuntu1) ...
Setting up python3.10 (3.10.4-3ubuntu0.1) ...
Setting up python3 (3.10.4-0ubuntu2) ...
running python rtupdate hooks for python3.10...
running python post-rtupdate hooks for python3.10...
Setting up systemd (249.11-0ubuntu3.4) ...
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service → /lib/systemd/system/getty@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target → /lib/systemd/system/remote-fs.target.
Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /lib/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.service → /lib/systemd/system/systemd-resolved.service.
ln: failed to create symbolic link '/etc/resolv.conf': Device or resource busy
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-pstore.service → /lib/systemd/system/systemd-pstore.service.
Initializing machine ID from D-Bus machine ID.
Setting up perl (5.34.0-3ubuntu1) ...
Setting up python3-gi (3.42.1-0ubuntu1) ...
Setting up systemd-timesyncd (249.11-0ubuntu3.4) ...
Created symlink /etc/systemd/system/dbus-org.freedesktop.timesync1.service → /lib/systemd/system/systemd-timesyncd.service.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service → /lib/systemd/system/systemd-timesyncd.service.
Setting up mailcap (3.70+nmu1ubuntu1) ...
Setting up python3-dbus (1.2.18-3build1) ...
Setting up mime-support (3.66) ...
Setting up php8.1-cli (8.1.2-1ubuntu2.2) ...
update-alternatives: using /usr/bin/php8.1 to provide /usr/bin/php (php) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/php.1.gz because associated file /usr/share/man/man1/php8.1.1.gz (of link group php) doesn't exist
update-alternatives: using /usr/bin/phar8.1 to provide /usr/bin/phar (phar) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/phar.1.gz because associated file /usr/share/man/man1/phar8.1.1.gz (of link group phar) doesn't exist
update-alternatives: using /usr/bin/phar.phar8.1 to provide /usr/bin/phar.phar (phar.phar) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/phar.phar.1.gz because associated file /usr/share/man/man1/phar.phar8.1.1.gz (of link group phar.phar) doesn't exist
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/cli/php.ini with new version
Setting up networkd-dispatcher (2.1-2ubuntu0.22.04.2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/networkd-dispatcher.service → /lib/systemd/system/networkd-dispatcher.service.
Setting up php8.1-fpm (8.1.2-1ubuntu2.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/php/8.1/fpm/php.ini with new version
Created symlink /etc/systemd/system/multi-user.target.wants/php8.1-fpm.service → /lib/systemd/system/php8.1-fpm.service.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up php-fpm (2:8.1+92ubuntu1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for php8.1-cli (8.1.2-1ubuntu2.2) ...
Processing triggers for php8.1-fpm (8.1.2-1ubuntu2.2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Removing intermediate container 0216ff5238b7
 ---> f3cdb020e648
Step 8/9 : EXPOSE 80
 ---> Running in 8810057c63b7
Removing intermediate container 8810057c63b7
 ---> fbcb9d33135e
Step 9/9 : CMD /usr/sbin/nginx -g "daemon off;"
 ---> Running in 4df8e8249305
Removing intermediate container 4df8e8249305
 ---> 0d522f287f08
Successfully built 0d522f287f08
Successfully tagged nginx_php-fpm:latest
nedokormysh@nedokormysh-VirtualBox:~$ sudo docker images
REPOSITORY      TAG       IMAGE ID       CREATED          SIZE
nginx_php-fpm   latest    0d522f287f08   9 seconds ago    307MB
<none>          <none>    6dcc17d9882b   4 minutes ago    169MB
<none>          <none>    b80d796839f1   14 minutes ago   169MB
ubuntu          latest    df5de72bdb3b   2 weeks ago      77.8MB
hello-world     latest    feb5d9fea6a5   10 months ago    13.3kB
nedokormysh@nedokormysh-VirtualBox:~$ 

